### ISSUE TITLE
Support for Polymer

### ISSUE THREAD

**Issue by JosefJezek** [prismicio/prismic-cli#1]
Could you add support for Polymer?

https://www.polymer-project.org/1.0/

Check out this elements for Firebase...
- https://github.com/firebase/polymerfire
- https://elements.polymer-project.org/elements/polymerfire
- https://elements.polymer-project.org/elements/app-storage?active=app-indexeddb-mirror

**Comment by arnaudlewis** [comment]
Hi @JosefJezek, Polymer shouldn't be an issue with the current javascript kit, could you build a little Polymer project just to get started and I can help you implement Prismic into it :)
