### ISSUE TITLE
Out of date dependency

### ISSUE THREAD

**Issue by asotog** [prismicio/prismic-cli#100]
Hi guys,

I tried CLI but I see, still adding old dependencies `prismic-javascript`, even though [documentation](https://prismic.io/docs/technologies/prismicio-client-technical-reference) shows this:

![image](https://user-images.githubusercontent.com/813023/121383059-6535aa00-c904-11eb-9e3e-5684dfbc9d1e.png)

**Comment by MarcMcIntosh** [comment]
hi @asotog  which framework are you experiencing this with?

**Comment by asotog** [comment]
hi, I'm adding prismic to a nextjs project

**Comment by MarcMcIntosh** [comment]
is this with the `new` command or the `theme` command?
The generator in `new` has been updated, but if it's a theme I'll need the url so I can pass this along :)
