### ISSUE TITLE
How to login to prismic-cli via GitHub account? 

### ISSUE THREAD

**Issue by kris10cabrera** [prismicio/prismic-cli#103]
I recently signed up for an account on `prismic.io` via my GitHub account. 

After running `prismic login` I am getting stuck at the requested `password` step as I never created a password since I am using the GitHub oAuth.

I am using`prismic-cli: 3.8.13`.

**Comment by Duaner** [comment]
Hey @kris10cabrera , 

We are currently working on this new feature. 
This should be available this month. 

We'll notify you when it's done.
