### ISSUE TITLE
[bug] `--no-prismic` flag disappeared with v4

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-cli#113]
v3 of the CLI included a `--no-prismic` flag to skip repo creation with `prismic sm --setup`. It looks like that flag is gone now, and it looks like some users are still trying to use it but getting an error:

![image](https://user-images.githubusercontent.com/31219208/128215835-c063a1e7-6835-4229-95cf-425552408a61.png)

**Comment by MarcMcIntosh** [comment]
Added here :)
https://github.com/prismicio/prismic-cli/pull/119
