### ISSUE TITLE
Support for oauth authentication

### ISSUE THREAD

**Issue by romariclaurent** [prismicio/prismic-cli#12]
Hi! 

Been trying to use prismic-cli on our cluster with OAuth, but the login step does not work. 
Looks like the `/authentication/signin?email=..&password=...` does not work with oauth.

As oauth servers can have different login strategies (we use login + password + one time code) it may be best to have the access_token directly sent to the `/authentication/signin` endpoint.

Of course the access_token should be validated. Most oauth2 systems generate JWT tokens that can be validated using a simple public key. 

I would be happy to help testing it! 

Thanks!

**Comment by srenault** [comment]
Hi Romaric,

The classic way is to generate a permanent access token on your side.
You will be able to provide it in the `prismic-cli` configuration.
Thanks to the permanent token, we will be able to genenrate a valid prismic session.

**Comment by romariclaurent** [comment]
@srenault great! let me know if you need help testing.
