### ISSUE TITLE
Could not resolve https://github.com/prismicio/vuejs-blog.git/archive/main.zip

### ISSUE THREAD

**Issue by tony19** [prismicio/prismic-cli#124]
Following the [*Run the theme command*](https://prismic.io/docs/technologies/example-projects-vuejs#run-the-theme-command) step from the docs, I see the following error:

```
$ npx prismic-cli theme --theme-url https://github.com/prismicio/vuejs-blog.git --conf public/index.html
Need to install the following packages:
  prismic-cli
Ok to proceed? (y) y
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Prismic: Press any key to open up the browser to login or q to exit: 
Opening browser to https://prismic.io/dashboard/cli/login?port=5555
Prismic: Logging in... Logged in as tony19@gmail.com
? Name your prismic repository:  https://blog-demo2.prismic.io
project folder [blog-demo2]: 
    Error: Could not resolve 
    https://github.com/prismicio/vuejs-blog.git/archive/main.zip or 
    https://github.com/prismicio/vuejs-blog.git/archive/master.zip
```

**Comment by tony19** [comment]
It seems the GitHub URLs to get a zipball/tarball no longer work:

```
https://github.com/prismicio/vuejs-blog.git/archive/master.zip
https://github.com/prismicio/vuejs-blog.git/archive/main.zip
```

However, this API URL works:

```
https://api.github.com/repos/prismicio/vuejs-blog/zipball/master
```

The code in `maybeGitHubRepo()` probably needs to be refactored to use that API URL:

https://github.com/prismicio/prismic-cli/blob/af9deb026972e636a9d9d1939e8edc763ee02a55/packages/prismic-cli/src/prismic/base-command.ts#L150-L153

**Comment by MarcMcIntosh** [comment]
HI @tony19 , thanks for pointing this out
Try with out putting .git at the end and that should work :)

**Comment by tony19** [comment]
Thanks that worked

**Comment by tony19** [comment]
I noticed the docs have not been updated to fix that typo. Is there a related commit for that?
