### ISSUE TITLE
Commands fail due to wrong path

### ISSUE THREAD

**Issue by javlund** [prismicio/prismic-cli#131]
Starting completely anew with Prismic, on a Windows 10 machine. Trying to run this example: https://prismic.io/docs/technologies/configure-your-project-nextjs

When I run this specific command:
`prismic theme --theme-url https://github.com/prismicio-community/slice-library-starter-next --conf sm.json`

I get this error: `Error: ENOENT: no such file or directory, scandir 'C:\Users\jacob\AppData\Roaming\nvm\v17.0.1\node_modules\prismic-cli\node_modules\generator-prismic-angular2\lib\generators'`

It's not surprising; when I navigate to `'C:\Users\jacob\AppData\Roaming\nvm\v17.0.1\node_modules\prismic-cli\node_modules\generator-prismic-angular2\`, I see that the `generators` folder is directly in this folder, not in an intermediate `lib` folder.

Same results when running `prismic list`.

I've also tried running this in a WSL2 Ubuntu environment to see if Windows was the culprit. Same issue.

**Comment by esplito** [comment]
I'm having the same problem on Mac OS Monterrey, running node v.17.0.1

**Comment by lihbr** [comment]
Hey there, thank you so much for your report!

Can you tell us which version of `prismic-cli` are you using? You can get it by running `prismic --version`

@MarcMcIntosh, can you have a look at it after? (maybe it's already fixed?)

**Comment by javlund** [comment]
> Hey there, thank you so much for your report!
> 
> Can you tell us which version of `prismic-cli` are you using? You can get it by running `prismic --version`
>

You're welcome - I used the newest at that time, pretty sure it was 4.2.0. Completely new install. Can't check anymore as I moved on to Strapi in order to get something up and running.

**Comment by esplito** [comment]
I'm also using 4.2.0. (`prismic-cli/4.2.0 darwin-x64 node-v17.0.1` is what I get from running `prismic --version`) :)

**Comment by MarcMcIntosh** [comment]
@esplito @javlund 
I see you're using node version 17, Is this only happening on node version 17?

**Comment by MarcMcIntosh** [comment]
I've managed to recreate the issue using nvm, node version 17 and `npx prismic-theme`

**Comment by javlund** [comment]
> @esplito @javlund I see you're using node version 17, Is this only happening on node version 17?

I think I tried downgrading to v16 with the same result, but I'm not 100% sure though.

**Comment by MarcMcIntosh** [comment]
I've not been able to recreate this issue when using node version 16 :/
17 on the other hand I can, I've opened up an issue on yeoman-environment asking if this is a version 17 specific issue.

I'll have to make some time to see if moving the directory to `lib` breaks the generators :)

**Comment by lihbr** [comment]
Thanks Marc! Node 17 is indeed a technology preview that was just released. That kind of bug can be expected and is likely to be fixed before next LTS (Node 18) release 🚀

_[Node releases](https://nodejs.org/en/about/releases)_

**Comment by MarcMcIntosh** [comment]
I wrote to the yeoman team asking if they knew about this issue, I'll have to free up some time to move the build files to the lib directory and confirm that resolves the issue and doesn't cause any more issues with older versions of node.

**Comment by MarcMcIntosh** [comment]
It seems a few more things break with node version 17 than just adding '/lib/generators/` to the lookup paths.
#134 
I'm still investigating these issues

**Comment by MarcMcIntosh** [comment]
@javlund @esplito A new version with the fix sound be released in the new year :)
Thanks for reporting the issue :)

**Comment by MarcMcIntosh** [comment]
@javlund @esplito 
A fix has been released. sorry it took so long :)
