### ISSUE TITLE
prismic-cli fails to login inside a docker container

### ISSUE THREAD

**Issue by itsjavi** [prismicio/prismic-cli#132]
I usually work in a dockerized development environment and, it seems it's not possible to make prismic-cli working inside a nodejs docker container.

The problem seems that it fails to open the browser (for obvious reasons, since containers cannot open dialogs of the host). I get this error:

```
Prismic: Press any key to open up the browser to login or q to exit: 
Opening browser to https://prismic.io/dashboard/cli/login?port=5555
Prismic: Logging in... done
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'https://prismic.io/dashboard/cli/login?port=5555' ]
}

```

Are you going to make this tool compatible with dockerized environments? 
Instead of opening the browser, it could ask the developer to click the link. I don't know if that would be enough, but at least the CLI login won't fail before attempting to login. After that I guess I need to expose port 5555 ?

Without this I cannot make slicemachine work unless it's installed in the host, which I'd rather avoid.

I tried using a text-based browser, [like proposed here](https://community.prismic.io/t/prismic-cli-login-over-ssh/6834/3), but it does not work.

**Comment by MarcMcIntosh** [comment]
Hello,

That's an interesting issue.

When the cli logins in, it'll add a token to `~/.prismic`, it should be possible to copy this file into the docker container. Although it will expire after after a day or two of not being used.
