### ISSUE TITLE
Module not found: Can't resolve 'prismic.io'

### ISSUE THREAD

**Issue by fwielstra** [prismicio/prismic-cli#19]
in Preview.js when using the React template.

Changing `import Prismic from 'prismic.io';` to `import Prismic from 'prismic-react';` fixed the issue, but I've not been able to find where exactly this import comes from.

**Comment by srenault** [comment]
Thanks for reporting this!
I just fixed it here: https://github.com/prismicio/reactjs-starter/commit/1a8c64b6fc91f4298be55b4d4b9b9116e442704d
