### ISSUE TITLE
Update repo-name anywhere

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-cli#23]
For some technologies we can't create a theme as they don't use the necessary prismic-configuration.js file. Can we update the cli to search all documents for the 'apiendpoint' to update it?

**Comment by hypervillain** [comment]
Hey @phillysnow, I'm working on a PR which allows you to specify a path to your configuration file. Would it work for you?

**Comment by phillysnow** [comment]
Yes, that sounds good to me.

**Comment by hypervillain** [comment]
Great, I just submitted the PR
