### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by WebShapedBiz** [prismicio/prismic-cli#28]
Hi.
There is a "Nuxt.js Sample multi-page website with navigation" sample on your website that I'm trying to follow. Unfortunately, running
`prismic theme https://github.com/prismicio/nuxtjs-website.git --conf prismic.config.js`,
I couldn't pass the account login step. No error displayed, just always back to asking my username and password again.

**Comment by michaelpumo** [comment]
Yes, I am also getting this issue when running: 

`prismic theme https://github.com/prismicio/gatsby-blog --conf prismic-config.js`

**Comment by arnaudlewis** [comment]
Try to logout and then try again.
We saw this issue and we’ll investigate it but that should help you move forward in the meantime ;)

**Comment by carnesen** [comment]
I encountered this too with the `prismic new` command. It got caught in a loop:
```
~ $ prismic new
Let's get to it!
? Name your prismic repository:  alwaysai-blog-test
? Local folder to initalize project:  alwaysai-blog-test
? Technology for your project:  React
? Do you already have an account on https://prismic.io? Yes, login to my existing account
? Email:  admin@alwaysai.co
? Password:  [hidden]
? Do you already have an account on https://prismic.io? Yes, login to my existing account
? Email:  admin@alwaysai.co
? Password:  [hidden]
...
```
As suggested, after running `prismic logout` I was able to complete the `prismic new` workflow.
