### ISSUE TITLE
Cannot login or initialize new projects

### ISSUE THREAD

**Issue by reinierkors** [prismicio/prismic-cli#44]
Hello,

I'm trying to start a new project using a theme, for example:
`prismic theme https://github.com/prismicio/nextjs-blog`

First of all, it does not detect the theme I entered. It asks: 
`URL of your theme (zip/github):`

Fine, I manually enter it.

Then I get to the login step, asks me for my password. I enter it and submit, and I get the following error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/prismic-cli/bin/services/communication/index.js:42:42
    at post (/usr/local/lib/node_modules/prismic-cli/bin/services/communication/index.js:48:4)
    at Object.postForm (/usr/local/lib/node_modules/prismic-cli/bin/services/communication/index.js:90:12)
    at /usr/local/lib/node_modules/prismic-cli/bin/commands/login.js:55:40
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Is Prismic CLI deprecated or not the recommended way to setup Prismic? If so, please guide me in the right direction.

I'm using NodeJS v12.17.0, Prismic-CLI 3.7.9.

**Comment by valentinvieriu** [comment]
I can confirm I have the same issue

**Comment by valentinvieriu** [comment]
I can confirm that starting with version 3.7.8 the `prismic login` does not work.
@reinierkors try installing `npm install -g prismic-cli@3.7.7` and use that version. This worked for me

**Comment by nytro04** [comment]
I was having the same issue till i run `prismic logout` and followed the process again. That worked for me.

**Comment by samueljoe7** [comment]
Thanks @nytro04 `prismic logout` followed by `prismic login` has resolved the issue for me. Using prismic-cli version 3.7.10

**Comment by valentinvieriu** [comment]
The interesting part is that I'm a first time user, so there is no way of logging out, as I've was never logged in.

**Comment by arnaudlewis** [comment]
Hello guys, for the login issue it should be okay with version `3.7.11` so don't hesitate to try it out and come back to yell at me if you see any other weird stuff going on :)
For the theme, it should have been part of a major version but to specify your theme url you must type the command this way: `prismic theme --theme-url <my_theme.url>`
Hope it helps!
