### ISSUE TITLE
Prismic Command Line Tool Installation failed

### ISSUE THREAD

**Issue by makwanahardik** [prismicio/prismic-cli#56]
node : v14.3.0
yarn : 1.22.4

![Screenshot 2020-08-06 at 3 31 12 PM](https://user-images.githubusercontent.com/32458204/89519393-ee1e1980-d7f9-11ea-849c-22b72ad65de7.png)

**Comment by phillysnow** [comment]
Hi @makwanahardik,

Can you try running `yarn global add prismic-cli@3.8.3-beta.0`?
