### ISSUE TITLE
[SliceMachine] Method Slices.createLocal breaks because it expects a valid path argument but receives an object

### ISSUE THREAD

**Issue by hypervillain** [prismicio/prismic-cli#58]
Method `Slices.createLocal` expects [a `pathToSlices` argument](https://github.com/prismicio/prismic-cli/blob/master/lib/commands/slicemachine/common/slices.js#L100) (a valid string path) but when it's called by the `--pull` command, an object containing the actual required path: https://github.com/prismicio/prismic-cli/blob/master/lib/commands/slicemachine/commands/pull.js#L89

**Comment by phillysnow** [comment]
`--pull` command deprecated in latest version of the CLI.
