### ISSUE TITLE
[RFC] Improve error message or add login check

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-cli#67]
**Issue:**
When running `prismic sm --create-slice` and you are not logged in you will get the error `Error: [fetch] An unexpected (401) Error occurred.`

**How to fix:**
This is fixed by logging in with the CLI so we should add a login check when running `prismic sm --create-slice`.

**Forum Thread of user issue:**
https://community.prismic.io/t/prismic-sm-create-slice-outputs-error-fetch-an-unexpected-401-error-occured/2350

**Comment by hypervillain** [comment]
`create-slice` should not ask for login anymore as it now only creates slices locally (3.8.0)
