### ISSUE TITLE
[RFC] Error message to alert users that they need to be on Slicemachine cluster

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-cli#68]
When running commands like `--create-slice` or `--pull` you will receive a 404 error, it would be more helpful if this error message indicated that you were not on a Slicemachine group and could request to be moved, [here on the forum](https://community.prismic.io/t/feature-activations-graphql-integration-fields-etc/847).

**Forum threads of users experiencing this:**
https://community.prismic.io/t/error-when-creating-a-slice-through-de-command-line-in-a-nuxt-project/2323
https://community.prismic.io/t/404ing-on-prismic-sm-pull-customtypes-endpoint/1726

**Comment by phillysnow** [comment]
Done on latest beta of the CLI.

**Comment by MarcMcIntosh** [comment]
in the cli we've removed the --pull command, and the create-slice command doesn't sync with prismic, slicemachine-ui handles that.
