### ISSUE TITLE
CLI fails to refresh token, not throwing on repository creation fail

### ISSUE THREAD

**Issue by lihbr** [prismicio/prismic-cli#69]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.3-beta.0

### Reproduction

1. Login with the CLI: `$ prismic login`
2. Create a new repo: `$ prismic new`
3. Create a second repo: `$ prismic new`

### What is expected?

Both repositories should be created.

### What is actually happening?

Only the first repository is created and the CLI does not throw when 2nd repository creation fails.

It also happens with other commands in charge of creating a repository: `$ prismic sm --setup`, `$ prismic sm --bootstrap`, etc.

### Any additional information

@arnaudlewis you mentioned one day that there's a need to refresh a token now, could it be something linked to that? Since there are two authentication methods now: https://github.com/prismicio/prismic-cli/blob/mm/meta-2020/lib/commands/repository.js#L55-L59

**Comment by MarcMcIntosh** [comment]
Inbetween doing the two new commands can you check the ~/.prismic file in your home directory.
it should have something like `{ base: ..., cookies: 'SESSION=....;prismic_auth=...}` I know one of the responses for set cookie cause the session to be removed.

**Comment by lihbr** [comment]
On login:
```json
{
    "cookies": "SESSION=XXX; Path=/; Domain=.prismic.io; Secure; HTTPOnly; SameSite=None;is-logged-in=1; Path=/; Domain=.prismic.io; Secure; SameSite=None;X_XSRF=XXX; Max-Age=315360000; Expires=Mon, 04 Nov 2030 12:55:19 GMT; Path=/; Domain=prismic.io; Secure; SameSite=None;prismic-auth=XXXs; Path=/; Domain=.prismic.io; Secure; SameSite=None",
    "base": "https://prismic.io"
}
```

After first `sm --bootstrap` (repo is created):
```json
{
    "cookies": "prismic-auth=XXX; Path=/; Domain=.prismic.io; Secure",
    "base": "https://prismic.io"
}
```

After second `sm --bootstrap` (repo is not created, no error thrown):
```json
{
    "cookies": "prismic-auth=XXX; Path=/; Domain=.prismic.io; Secure",
    "base": "https://prismic.io"
}
```

🤔

**Comment by MarcMcIntosh** [comment]
Yes, that was fixed in the alpha version, here https://github.com/prismicio/prismic-cli/pull/65/commits/b54831bbd365216533e19ba5532cf32b520ffc03

Our cookie implementation could do with refactoring as there's a few places the cookies are set and parsed.

**Comment by MarcMcIntosh** [comment]
Either way giving some feedback that there was an error is a good idea :)

**Comment by lihbr** [comment]
It'll be nice to throw in case repo creation fail still 🤔
