### ISSUE TITLE
Question - How to practice configuration as code with prismic?

### ISSUE THREAD

**Issue by StarpTech** [prismicio/prismic-cli#74]
Hello,
we switched from Ghost to Prismic to be more flexible. I didn't expect that there is no way to import data except the manual import on the medium plan. For me, this is a deal-breaker because I can't migrate schema updates or store the schema as code next to my application code. In the past, I used contentful and commercetools. They both provided at least a CLI to do that. Some even shipped terraform support https://github.com/labd/terraform-provider-commercetools.

According to https://prismic.io/docs/technologies/does-prismic-have-a-write-api there isn't a write API. This also blocks innovations from the community. What's the long term vision of prismic here? Thank you!

Related https://github.com/prismicio/prismic-cli/issues/11

**Comment by MarcMcIntosh** [comment]
HI @StarpTech 

Yes, unfortunately we don't have a write-api for documents... 

but we have been working on slicemachine and introducing a custom-types api https://prismic.io/docs/technologies/custom-types-api

Slicemachine enables you to work with schemas in the codebase (just slices for now) and then push them to prismic so content can be added :)

You can try out slicemachine today , it works with next or nuxt https://www.slicemachine.dev/

DId that answer you questions?
