### ISSUE TITLE
Default Route Resolver causes bugs with `prismic sm --setup --no-prismic`

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-cli#75]
Users can run `prismic sm --setup --no-prismic` to build out a project. In Nuxt, the command adds a Route Resolver to `nuxt.config.js`. However, the Route Resolver references custom types that don't necessarily exist. So, when the user makes a query, they get an error. It would be good if `--no-prismic` didn't create a Route Resolver.

**Comment by lihbr** [comment]
I think this will get handled with the new CLI, in any case @MarcMcIntosh 🙂

**Comment by MarcMcIntosh** [comment]
I've removed the --no-prismic flag :)
we should discuss this further with @Duaner

**Comment by MarcMcIntosh** [comment]
`--no-prismic` has be renamed and added here https://github.com/prismicio/prismic-cli/pull/119

We'll have to look at the route resolver issue
