### ISSUE TITLE
`prismic init` prompts to name a repository

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-cli#76]
`prismic init` prompts the user to name a repository, suggesting that it's creating a new repo. If the user enters a name for a new repo, it throws an error. The prompt should say something like, "Enter the name of the Prismic repo you would like to use."
<img width="710" alt="Screen Shot 2021-01-14 at 1 51 39 PM" src="https://user-images.githubusercontent.com/31219208/104593474-0aa76300-5670-11eb-86d6-5275eb4923db.png">

**Comment by lihbr** [comment]
Fancy screenshot 👀 I think @MarcMcIntosh was handling that with the CLI refactor!

**Comment by MarcMcIntosh** [comment]
I think we removed the init command as it was undocumented
