### ISSUE TITLE
[RFC] Dynamically update slice function name in generate template.

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-cli#78]
It would be nice that when a new Slice template in Next.js is created, that the Slice function name is also update from MySlice to what ever name was entered in the CLI prompt:
https://github.com/prismicio/prismic-cli/blob/master/lib/commands/slicemachine/templates/next/index.js

The same could be said for the Nuxt.js template to have the field `name: 'SliceName'` added to the script section of the component as well:
https://github.com/prismicio/prismic-cli/blob/master/lib/commands/slicemachine/templates/nuxt/index.vue

**Comment by ReeceM** [comment]
I was looking through the code related to creating slices, and it appears that Mustache is already being used for the model file and. It could be possible to use the same for the others? Or even a regex and replace function of a defined search pattern while / before copying it over to the users project file, although the mustache syntax is about the same anyways.

Also, I was trying to look for where this code was in the wrong repository 🤣 

Thank you for having a look/ or possibly considering it 👍

**Comment by MarcMcIntosh** [comment]
Hi this feature has been added to an upstream branch

**Comment by ReeceM** [comment]
Thanks @MarcMcIntosh 👍 

I think I saw a little bit of the edits the other day in the one branch.
