### ISSUE TITLE
SliceMachine 'next steps' links 404

### ISSUE THREAD

**Issue by a-trost** [prismicio/prismic-cli#79]
## Version
3.8.7

## Reproduction
Bring `prismic sm --setup` to completion.
You are then presented this screen:
![image](https://user-images.githubusercontent.com/19617280/107877118-61cf6c00-6e98-11eb-8509-cee64f063132.png)

## What is expected?
That the links in this section take me to live documentation so I can continue to build my SliceMachine site.

## What is actually happening?
Some of the links 404.

When you complete the SliceMachine setup you are given "Next Steps" which comes from this file:
https://github.com/prismicio/prismic-cli/blob/34b6b4b0c04be2041186b28d027e4033ccc95be3/lib/commands/slicemachine/misc/recap.mustache

These links need to be updated to account for the migration from docs living on slicemachine.dev.
https://github.com/prismicio/prismic-cli/blob/34b6b4b0c04be2041186b28d027e4033ccc95be3/lib/commands/slicemachine/commands/init.js#L75-L82

We can't just swap out the links for updated ones, because it seems there is no generic "Add Slice Zone" doc anymore. 
![image](https://user-images.githubusercontent.com/19617280/107876914-02249100-6e97-11eb-9099-6a99aa703f44.png)

It's either a Nuxt or a Next Slice Zone link, so the CLI needs to either link to both, or conditionally show one or the other.

**Comment by Duaner** [comment]
Hey @MarcMcIntosh this seems to be related to the fact that we don't check if the user token is still relevant and valid. If it's not we still try to create the repo that fails because the token is expired. 

We should check if the token is expired, then refresh it if it's the case.

Can we pass a quick fix for that without waiting for the refacto?

**Comment by MarcMcIntosh** [comment]
Wait, how do the links relate to the token?
I guess this link would require repo-creation.
```js
{ 
  writingRoomUrl: info.apiEndpoint ? `${info.apiEndpoint.split('/api')[0].replace('cdn.', '')}/documents` : 'https://prismic.io/dahboard', 
}
 ```

Is there a refresh endpoint to check tokens?, 
I've asked a few times before about this and have been told to that the cli attempts the creation catch's an error and then prompt the user to login and try again if it's a 401 error. 
 
This should still be the behaviour, I can check and see. 
I'd would be happy to add a check if we have an endpoint for refreshing tokens :)

**Comment by Duaner** [comment]
@MarcMcIntosh Following our discussion, the problem is when you actually have a token that is invalid not when you don't have a token. 

You now have a refresh endpoint to check the validity of the token and should check it first

**Comment by MarcMcIntosh** [comment]
Nice, what about these two links?
https://www.slicemachine.dev/documentation/slicezone
https://slicemachine.dev/documentation/creating-your-own-components-slices
