### ISSUE TITLE
[RFC] Add 'whoami' command 

### ISSUE THREAD

**Issue by a-trost** [prismicio/prismic-cli#81]
We have a `prismic login` and `prismic logout,` but no way to tell what my current user is. In order to make sure I'm on the right account before I start running Prismic commands I need to logout and log back in.

So something like `prismic whoami` that would return either the current user's email address or a "you are not logged in" response.

**Comment by lihbr** [comment]
@MarcMcIntosh nice idea imho!

**Comment by MarcMcIntosh** [comment]
Yes @faresd also mentioned this a while ago, I'll have to look and see if there are any end points that can be safely used to get user information

**Comment by lihbr** [comment]
When you log in you provide your email, why not just saving this mail at `~/.prismic` along the access token & cookies, and removing it upon log out?

**Comment by MarcMcIntosh** [comment]
could do :)

**Comment by lihbr** [comment]
You rock!

**Comment by MarcMcIntosh** [comment]
What about people that use an oath token to login?

**Comment by lihbr** [comment]
No idea, there are multiple ways to log in?

**Comment by MarcMcIntosh** [comment]
Yes, I've added the command to the mm/oclif branch :)

**Comment by MarcMcIntosh** [comment]
add in unrelease mm/oclif branch
