### ISSUE TITLE
Gatsby step-by-step tutorial doesn't work out of the box

### ISSUE THREAD

**Issue by emmmarosewalker** [prismicio/prismic-cli#84]
After following the steps exactly in the https://prismic.io/docs/technologies/step-by-step-guide-gatsby my repo is created on prismic.io but no data is pulled in. The example graphql query also doesn't return the expected data. 

`{
  "data": {
    "allPrismicHomepage": {
      "edges": []
    }
  },
  "extensions": {}
}`

**Comment by pvpg** [comment]
Hello @emmmarosewalker. It is weird because if the repository was correctly created, then the query should work. Did you run it in the GraphQL playground?

Maybe it is something related to your plugin configuration. Could you share it here with us so we can take a look?
