### ISSUE TITLE
Registry configuration is being overwritten

### ISSUE THREAD

**Issue by Daeluse** [prismicio/prismic-cli#87]
Tracking down an issue we have been having relating to using Prismic behind a JFrog AF instance. The issue we had was that the package always tries to use the npmjs registry to look for newer available versions. Since this url is blocked by our network, that was always causing an issue.

A fix was implemented as part of 21e05bb6a6f7dd15911d9f0755b693b900e981c7 which added libnpmconfig to source the registry from the config, but it looks like the package is not functioning correctly as the following line will ALWAYS override the config with the 'default' registry.

```javascript
const config = libnpmconfig.read({ registry: 'https://registry.npmjs.org/' });
````

The next hurdle we had to overcome was authenticating with the private registry. Typical authentication uses a config variable named `_auth` to store a token applied to the Authorization header using Basic auth. To overcome this, I had to make the following modifications.

```javascript
var token = '<PUT YOUR TOKEN HERE>';

return (0, _nodeFetch["default"])(addr.toString(), {
  headers: {
    Accept: 'application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*',
    'Accept-Encoding': 'gzip,deflate',
    Authorization: 'Basic ' + token,
    'Content-Type': 'application/json',
    'Connection': 'keep-alive',
  }
}).then(function (res) {
  console.log("Successfully fetched".concat(packageName, " from ").concat(addr));
  return res.json();
}).catch(function (err) {
  console.error("Failed to fetch ".concat(packageName, " from ").concat(addr));
  throw err;
});
```

EDIT: One last thing to mention, I also had to update the strategy for specifying the URL of the package. JFrog AF registries have a trailing path name to specify the virtual before the package name, so updating the pathname directly was causing issue. This was my workaround:

```javascript
var addr = new URL(config.registry.concat(packageName));
```

Obviously this is specific to my use case, and does not source the `_auth` token from the config (libnpmconfig does not return it).

Any chance we could get these fixes worked appropriately and implemented? This issue is directly related to the community post at https://community.prismic.io/t/cannot-login-to-prismic-cli/4830.

**Comment by MarcMcIntosh** [comment]
Hi @Daeluse You're right about libnpmconfig... it's on that's not the behavour that the readme says it should have :/

That sounds like a lot of hassle, I'll take out the automatic version checking for now, until we figure  out a more reliable way to check the most recent package version from a range of hosts.

That means the version command will be broken but the rest of the cli should continue to work. :)
