### ISSUE TITLE
Syncing custom_types and slices from the CLI

### ISSUE THREAD

**Issue by Bram-Zijp** [prismicio/prismic-cli#91]
As I wanted to have my types managed in code (and only in code), I hacked together a sync command in a fork. The code is not that good. I didn't feel like spending time on refactoring properly after getting it to work (as *I desired* at the moment of writing). I can imagine Prismic has their own views of how to add these type of functionality. This fork will hopefully become redundant.

I added these sync methods as the API and Prismic CLI were capable already. Besides, it didn't take to long to implement :smile: I am hoping for a clean out of the box way of Prismic to offer this functionality. Feel free to use this fork as you desire.

I would not recommend using this fork in production. I worked with very little insights and just copied what was already implemented in one of prismic's it's repo's and adjusted it to make it work (slice-machine-ui, prismic-cli).

For demoing purposes only. **I'm not responsible if you destroy your production environment or any other environment**: https://github.com/Bram-Zijp/prismic-cli/pull/1

**Comment by lihbr** [comment]
Hey @Bram-Zijp, thanks for sharing your work on this fork! That can be helpful to some people indeed and as you mentioned it everyone's free to use it at their own risks!

Moving forward, we might not need this type of sync anymore as we're working on making git repositories the source of truth for Prismic custom types! You might be interested to have a read here: https://github.com/prismicio/slice-machine/issues/91

Have a great day!
